---
title: "bb_simulation"
author: "Rune Rathmann"
date: "22/5/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# Prediction Model
## Train Model
```{r}
library(caret)
bb <- read.csv("C:/Users/runer/OneDrive/Dokumenter/MSc/8th Semester/Data Science Project/WSB Project/PredictStockusingRedditandTwitter/PreProcessedData/bb_merged.csv")

bb <- bb[,-c(1:7)]
bb <- bb[-48,]

## make lead_movement factor (for the SVM model)
bb$lead_movement <- as.factor(bb$lead_movement)

## ad lagged variables
# lag 1 bb
bb$pos_lag1 <- dplyr::lag(bb[ , 1], 1L)
bb$neg_lag1 <- dplyr::lag(bb[ , 2], 1L)
bb$lit_lag1 <- dplyr::lag(bb[ , 3], 1L)
bb$sup_lag1 <- dplyr::lag(bb[ , 4], 1L)
bb$con_lag1 <- dplyr::lag(bb[ , 5], 1L)
bb$unc_lag1 <- dplyr::lag(bb[ , 6], 1L)

# lag 2 bb
bb$pos_lag2 <- dplyr::lag(bb[ , 1], 2L)
bb$neg_lag2 <- dplyr::lag(bb[ , 2], 2L)
bb$lit_lag2 <- dplyr::lag(bb[ , 3], 2L)
bb$sup_lag2 <- dplyr::lag(bb[ , 4], 2L)
bb$con_lag2 <- dplyr::lag(bb[ , 5], 2L)
bb$unc_lag2 <- dplyr::lag(bb[ , 6], 2L)

# lag 3 bb
bb$pos_lag3 <- dplyr::lag(bb[ , 1], 3L)
bb$neg_lag3 <- dplyr::lag(bb[ , 2], 3L)
bb$lit_lag3 <- dplyr::lag(bb[ , 3], 3L)
bb$sup_lag3 <- dplyr::lag(bb[ , 4], 3L)
bb$con_lag3 <- dplyr::lag(bb[ , 5], 3L)
bb$unc_lag3 <- dplyr::lag(bb[ , 6], 3L)


train.bb <- bb[4:35,]
test.bb <- bb[36:47,]

trControl <- trainControl(method = 'timeslice',
                          initialWindow = 8,
                          horizon = 6,
                          fixedWindow = FALSE
)

set.seed(2)
POLY.SVM.bb <- train(lead_movement ~ ., data = train.bb, 
                      method = 'svmPoly',
                      trControl = trControl,
                      family = 'binomial', 
                      metric = "Accuracy",
                      tuneLength= 5)

```

## Make Predictions
```{r}
  # Making predictions on test data with the best model
  pred <- predict(POLY.SVM.bb, newdata=test.bb)

cm <- confusionMatrix(
  pred, 
  test.bb$lead_movement)
```


## create prediction result table
```{r}
pred.bb <- cbind(test.bb$lead_movement,pred)-1
```

## Get Absolute Prices
```{r}
bb.prices <- read.csv("C:/Users/runer/OneDrive/Dokumenter/MSc/8th Semester/Data Science Project/WSB Project/PredictStockusingRedditandTwitter/PreProcessedData/bb_merged.csv")

bb.prices <- bb.prices[-48,c(1,2,5,14)]
bb.prices <- bb.prices[36:47,]

sim <- cbind(bb.prices,pred)
```

# Prediction Simulation
```{r}
library(dplyr)

sim$Acc.Volume = 0  
sim <- sim %>%
mutate(DateTime = as.POSIXct(created_utc)) %>% 
mutate(Purchase = ifelse(pred == 1,open*100,0)) %>%
mutate(Volume = ifelse(pred == 1,100,0))

sim$Acc.Volume <- with(sim,ave(Volume,cumsum(Volume==0),FUN=cumsum))

sim <- sim %>%    
mutate(Sell = ifelse(pred == 1,0,lag(Acc.Volume, n = 1L)*open)) %>%
mutate(Profit = Sell-Purchase)

rest_sell <- sim[length(sim$open),"Acc.Volume"]*sim[length(sim$open),3]

profit <- sum(sim$Profit[2:length(sim$Profit)])+rest_sell

as.matrix(sim$Profit)

```

```{r}
ggplot(data=sim, aes(x=created_utc, y=close, group=1)) +
  geom_line(color="red")+
  geom_point()+
  theme(axis.text.x = element_text(angle = 45, hjust=1))
```

