---
title: "pltr_simulation"
author: "Rune Rathmann"
date: "22/5/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# Prediction Model
## Train Model
```{r}
library(caret)
pltr <- read.csv("C:/Users/runer/OneDrive/Dokumenter/MSc/8th Semester/Data Science Project/WSB Project/PredictStockusingRedditandTwitter/PreProcessedData/pltr_merged.csv")

pltr <- pltr[,-c(1:7)]
pltr <- pltr[-48,]

## make lead_movement factor (for the SVM model)
pltr$lead_movement <- as.factor(pltr$lead_movement)

## ad lagged variables
# lag 1 pltr
pltr$pos_lag1 <- dplyr::lag(pltr[ , 1], 1L)
pltr$neg_lag1 <- dplyr::lag(pltr[ , 2], 1L)
pltr$lit_lag1 <- dplyr::lag(pltr[ , 3], 1L)
pltr$sup_lag1 <- dplyr::lag(pltr[ , 4], 1L)
pltr$con_lag1 <- dplyr::lag(pltr[ , 5], 1L)
pltr$unc_lag1 <- dplyr::lag(pltr[ , 6], 1L)

# lag 2 pltr
pltr$pos_lag2 <- dplyr::lag(pltr[ , 1], 2L)
pltr$neg_lag2 <- dplyr::lag(pltr[ , 2], 2L)
pltr$lit_lag2 <- dplyr::lag(pltr[ , 3], 2L)
pltr$sup_lag2 <- dplyr::lag(pltr[ , 4], 2L)
pltr$con_lag2 <- dplyr::lag(pltr[ , 5], 2L)
pltr$unc_lag2 <- dplyr::lag(pltr[ , 6], 2L)

# lag 3 pltr
pltr$pos_lag3 <- dplyr::lag(pltr[ , 1], 3L)
pltr$neg_lag3 <- dplyr::lag(pltr[ , 2], 3L)
pltr$lit_lag3 <- dplyr::lag(pltr[ , 3], 3L)
pltr$sup_lag3 <- dplyr::lag(pltr[ , 4], 3L)
pltr$con_lag3 <- dplyr::lag(pltr[ , 5], 3L)
pltr$unc_lag3 <- dplyr::lag(pltr[ , 6], 3L)


train.pltr <- pltr[4:35,]
test.pltr <- pltr[36:47,]

trControl <- trainControl(method = 'timeslice',
                          initialWindow = 8,
                          horizon = 6,
                          fixedWindow = FALSE
)

set.seed(2)
POLY.SVM.pltr <- train(lead_movement ~ ., data = train.pltr, 
                      method = 'svmPoly',
                      trControl = trControl,
                      family = 'binomial', 
                      metric = "Accuracy",
                      tuneLength= 5)

```

## Make Predictions
```{r}
  # Making predictions on test data with the best model
  pred <- predict(POLY.SVM.pltr, newdata=test.pltr)

cm <- confusionMatrix(
  pred, 
  test.pltr$lead_movement)
```


## create prediction result table
```{r}
pred.pltr <- cbind(test.pltr$lead_movement,pred)-1
```

## Get Absolute Prices
```{r}
pltr.prices <- read.csv("C:/Users/runer/OneDrive/Dokumenter/MSc/8th Semester/Data Science Project/WSB Project/PredictStockusingRedditandTwitter/PreProcessedData/pltr_merged.csv")

pltr.prices <- pltr.prices[-48,c(1,2,5,14)]
pltr.prices <- pltr.prices[36:47,]

sim <- cbind(pltr.prices,pred)
```

# Prediction Simulation
```{r}
library(dplyr)

sim$Acc.Volume = 0  
sim <- sim %>%
mutate(Purchase = ifelse(pred == 1,close*100,0)) %>%
mutate(Volume = ifelse(pred == 1,100,0))

sim$Acc.Volume <- with(sim,ave(Volume,cumsum(Volume==0),FUN=cumsum))

sim <- sim %>%    
mutate(Sell = ifelse(pred == 1,0,lag(Acc.Volume, n = 1L)*close)) %>%
mutate(Profit = Sell-Purchase)

rest_sell <- sim[length(sim$close),"Acc.Volume"]*sim[length(sim$close),3]

profit <- sum(sim$Profit[2:length(sim$Profit)])+rest_sell

View(sim)
```

