---
title: "tsla_simulation"
author: "Rune Rathmann"
date: "22/5/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```





# Prediction Model
## Train Model
```{r}
library(caret)
tsla <- read.csv("C:/Users/runer/OneDrive/Dokumenter/MSc/8th Semester/Data Science Project/WSB Project/PredictStockusingRedditandTwitter/PreProcessedData/tsla_merged.csv")

tsla <- tsla[,-c(1:7)]
tsla <- tsla[-48,]

## make lead_movement factor (for the SVM model)
tsla$lead_movement <- as.factor(tsla$lead_movement)

## ad lagged variables
# lag 1 tsla
tsla$pos_lag1 <- dplyr::lag(tsla[ , 1], 1L)
tsla$neg_lag1 <- dplyr::lag(tsla[ , 2], 1L)
tsla$lit_lag1 <- dplyr::lag(tsla[ , 3], 1L)
tsla$sup_lag1 <- dplyr::lag(tsla[ , 4], 1L)
tsla$con_lag1 <- dplyr::lag(tsla[ , 5], 1L)
tsla$unc_lag1 <- dplyr::lag(tsla[ , 6], 1L)

# lag 2 tsla
tsla$pos_lag2 <- dplyr::lag(tsla[ , 1], 2L)
tsla$neg_lag2 <- dplyr::lag(tsla[ , 2], 2L)
tsla$lit_lag2 <- dplyr::lag(tsla[ , 3], 2L)
tsla$sup_lag2 <- dplyr::lag(tsla[ , 4], 2L)
tsla$con_lag2 <- dplyr::lag(tsla[ , 5], 2L)
tsla$unc_lag2 <- dplyr::lag(tsla[ , 6], 2L)

# lag 3 tsla
tsla$pos_lag3 <- dplyr::lag(tsla[ , 1], 3L)
tsla$neg_lag3 <- dplyr::lag(tsla[ , 2], 3L)
tsla$lit_lag3 <- dplyr::lag(tsla[ , 3], 3L)
tsla$sup_lag3 <- dplyr::lag(tsla[ , 4], 3L)
tsla$con_lag3 <- dplyr::lag(tsla[ , 5], 3L)
tsla$unc_lag3 <- dplyr::lag(tsla[ , 6], 3L)


train.tsla <- tsla[4:35,]
test.tsla <- tsla[36:47,]

trControl <- trainControl(method = 'timeslice',
                          initialWindow = 8,
                          horizon = 6,
                          fixedWindow = FALSE
)

set.seed(2)
POLY.SVM.tsla <- train(lead_movement ~ ., data = train.tsla, 
                      method = 'svmPoly',
                      trControl = trControl,
                      family = 'binomial', 
                      metric = "Accuracy",
                      tuneLength= 5)

```

## Make Predictions
```{r}
  # Making predictions on test data with the best model
  pred <- predict(POLY.SVM.tsla, newdata=test.tsla)

cm <- confusionMatrix(
  pred, 
  test.tsla$lead_movement)
```


## create prediction result table
```{r}
pred.tsla <- cbind(test.tsla$lead_movement,pred)-1
```

## Get Absolute Prices
```{r}
tsla.prices <- read.csv("C:/Users/runer/OneDrive/Dokumenter/MSc/8th Semester/Data Science Project/WSB Project/PredictStockusingRedditandTwitter/PreProcessedData/tsla_merged.csv")

tsla.prices <- tsla.prices[-48,c(1,2,5,14)]
tsla.prices <- tsla.prices[36:47,]

sim <- cbind(tsla.prices,pred)
```

# Prediction Simulation
```{r}
library(dplyr)

sim$Acc.Volume = 0  
sim <- sim %>%
mutate(Purchase = ifelse(pred == 1,close*100,0)) %>%
mutate(Volume = ifelse(pred == 1,100,0))

sim$Acc.Volume <- with(sim,ave(Volume,cumsum(Volume==0),FUN=cumsum))

sim <- sim %>%    
mutate(Sell = ifelse(pred == 1,0,lag(Acc.Volume, n = 1L)*close)) %>%
mutate(Profit = Sell-Purchase)

rest_sell <- sim[length(sim$close),"Acc.Volume"]*sim[length(sim$close),3]

profit <- sum(sim$Profit[2:length(sim$Profit)])+rest_sell

```
